// Side-effect imports of stylesheets, e.g. `import "./globals.css"` in
// app/layout.tsx.
//
// Next.js normally declares these via next-env.d.ts, but that file is
// generated by `next dev`/`next build` and is gitignored, so it does not
// exist in CI — `pnpm type-check` there fails with:
//   TS2882: Cannot find module or type declarations for side-effect import
// Declaring them here keeps type-check independent of generated files.
declare module "*.css"
declare module "*.scss"
